# Generated by Django 5.0.3 on 2024-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, choices=[('Marin', 'Marin'), ('Air', 'Air'), ('Land', 'Land')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Product', 'Product'), ('Solution', 'Solution')], max_length=25, null=True),
        ),
    ]
