# Generated by Django 5.0.3 on 2024-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_application_type_remove_product_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.ManyToManyField(related_name='products', to='product.application'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(related_name='products', to='product.type'),
        ),
    ]
