# Generated by Django 5.0.3 on 2024-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_application_alter_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': True, 'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_pdf',
            field=models.FileField(default=1, upload_to='products/product_pdf/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='',
        ),
    ]
