# Generated by Django 5.0.3 on 2024-03-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='similar_products',
            new_name='similar_tags',
        ),
    ]
