# Generated by Django 5.0.3 on 2024-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
