# Generated by Django 5.0.3 on 2024-03-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contents', to='product.product'),
        ),
    ]
