# Generated by Django 5.0.3 on 2024-04-04 22:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
